export const environment = {
  production: true,
  beta: false,
  MATOMO_URL: '',
  MATOMO_SITE: -1,
  API_LOGIN: '/api',
  API_ENDPOINT: '/api',
  API_TOKEN_ENDPOINT: '',
  projectName: 'Observatory',
  projectMail: 'example@oac.eu',
  serviceORresource: 'Resource',
  hasUserConsent: true,
  showHelpContent: false,
  privacyPolicyURL: '',
  marketplaceBaseURL: '',
  STATS_API_ENDPOINT: '/stats/api/',
  profileName: 'eosc-obs',
  OSO_STATS_API_ENDPOINT: 'https://services.openaire.eu/stats-tool/',
  osoStatsProfileName: 'observatory'
};
